campus_supermarket/urls.py
import django
from django.conf.urls import url, include

from campus_supermarket import settings
from goods import views

urlpatterns = [
    url(r'^admin/', include('cs_admin.urls', namespace='cs_admin')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^index/', views.index),
    url(r'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT}),

]

user/urls.py
from django.conf.urls import url

from user import views

app_name = 'user'
urlpatterns = [
    # 注册
    url(r'^register/', views.register, name='register'),
    # 登陆
    url(r'^login/', views.login, name='login'),
    # 退出
    url(r'^logout/', views.logout, name='logout'),
    # 编辑
    url(r'^basic_info/$', views.basic_info, name='basic_info'),
    url(r'^edit_basic_info/$', views.edit_basic_info, name='edit_basic_info'),
    url(r'^account_security/$', views.account_security, name='account_security'),
    url(r'^address/$', views.address, name='address'),

]

user/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    username = models.CharField(max_length=32, unique=True)      # 用户名
    nickname = models.CharField(max_length=32)  # 昵称
    password = models.CharField(max_length=256)                  # 密码
    email = models.CharField(max_length=64, unique=True)         # 邮箱
    gender = models.CharField(max_length=10)  # 性别
    birth_date = models.DateField(max_length=32)  # 出生日期
    phone = models.CharField(max_length=11, default='')          # 收件人电话
    direction = models.CharField(max_length=100, default='')     # 收货地址

    class Meta:
        db_table = 'user'

user/views.py
from datetime import datetime, timedelta

from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from user.models import User
# Create your views here.


def login(request):
    if request.method == 'GET':
        return render(request, 'user/login.html')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('pwd')
        print(username)
        print(password)
        # 验证用户是否注册
        if User.objects.filter(username=username).exists():
            user = User.objects.get(username=username)
            # 验证密码是否正确
            if password == user.password:
                request.session['user_id'] = user.id
                return HttpResponse("登录成功！")
            else:
                return HttpResponse("用户名或密码错误！")
        else:
            return HttpResponse("用户名不存在,请注册后再登陆!")


def logout(request):
    try:
        del request.session['user_id']
    except:
        pass
    finally:
        return redirect(reverse('user:login'))


def register(request):
    if request.method == 'GET':
        return render(request, 'user/register.html')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('pwd')
        email = request.POST.get("email")
        if User.objects.filter(username=username):
            return HttpResponse("用户名已被占用！")
        if User.objects.filter(email=email):
            return HttpResponse("邮箱已被占用！")
        User.objects.create(username=username, password=password, email=email)
        return HttpResponse("注册成功！请返回登录")


def basic_info(request):
    if request.method == 'GET':
        user = User.objects.get(id=request.session.get('user_id'))
        return render(request, 'user/user_center/basic_info.html', {'user': user})
    elif request.method == 'POST':
        pass


def edit_basic_info(request):
    user = User.objects.get(id=request.session.get('user_id'))
    if request.method == "GET":
        return render(request, 'user/user_center/edit_basic_info.html', {'user': user})
    elif request.method == "POST":
        user.username = request.POST.get("username") if request.POST.get("username") else user.username
        user.nickname = request.POST.get("nickname") if request.POST.get("nickname") else user.nickname
        user.gender = request.POST.get("gender") if request.POST.get("gender") else user.gender
        user.birth_date = request.POST.get("birth_date") if request.POST.get("birth_date") else user.birth_date
        user.phone = request.POST.get("phone") if request.POST.get("phone") else user.phone
        user.email = request.POST.get("email") if request.POST.get("email") else user.email
        user.save()
        redirect(reverse('user:basic_info'))
        return render(request, 'user/user_center/basic_info.html', {'user': user})


def account_security(request):
    user = User.objects.get(id=request.session.get('user_id'))
    if request.method == 'GET':
        return render(request, 'user/user_center/account_security.html', {'user': user})
    elif request.method == 'POST':
        old_pwd = request.POST.get("old_pwd")
        if old_pwd != user.password:
            return HttpResponse("false")
        else:
            user.password = request.POST.get("new_pwd")
            user.save()
            return render(request, 'user/user_center/account_security.html', {'user': user})


def address(request):
    user = User.objects.get(id=request.session.get('user_id'))
    if request.method == 'GET':
        return render(request, 'user/user_center/address.html', {'user': user})
    elif request.method == 'POST':
        user.direction = request.POST.get("address");
        user.save()
        return render(request, 'user/user_center/address.html', {'user': user})

templates/user/user_center/account_security.html
{% extends 'user/user_center/usercenter_base.html' %}
{% block user_center %}
    <style>
        .edit_pwd_form {
            display: none;
            width: 500px;
            height: 250px;
            margin: 10px auto 0 30px
        }

        .edit_pwd_form label {
            width: 100px;
            float: left;
            clear: both;
            text-align: center
        }

        .edit_pwd_form label, input {
            margin: 10px auto;
            height: 20px;
            float: left
        }

        #submit_pwd_btn {
            width: 100px;
            height: 30px;
            margin-left: 100px;
            clear: both
        }

        #edit_pwd_btn {
            width: 100px;
            height: 30px;
            margin-left: 50px;
            margin-top: 20px;
        }
    </style>
    <h3 style="margin: 30px auto 0 50px">账户与安全</h3>
    <button id="edit_pwd_btn">修改密码</button>
    <form action="{% url 'user:account_security' %}" class="edit_pwd_form" id="edit_pwd_form" method="post">
        <label for="">原密码：</label>
        <input type="password" name="old_pwd">
        <span id="msg1" style="float:left;height: 20px;line-height: 20px;margin: 10px 0 0 10px;color:red"></span>
        <label for="">新密码:</label>
        <input type="password" name="new_pwd">
        <label for="" style="margin-bottom: 0">确认密码：</label>
        <input type="password" name="new_pwd_confirm" style="margin-bottom: 0">
        <span id="msg2"
              style="float:left;height: 20px;line-height: 20px;margin: 13px 0 0 10px;color:red;display: inline-block"></span>
        <input type="button" value="提交" id="submit_pwd_btn">
    </form>

    <script>
        var edit_pwd_btn = document.getElementById("edit_pwd_btn"),
            edit_pwd_form = document.getElementById("edit_pwd_form"),
            submit_pwd_btn = document.getElementById("submit_pwd_btn");
        var inputs = edit_pwd_form.getElementsByTagName("input");
        var xhr = null;
        window.onload = function () {
            edit_pwd_btn.onclick = function () {
                edit_pwd_btn.style.display = "none";
                edit_pwd_form.style.display = "block";
            };
            for (let i = 0; i < inputs.length; i++) {
                inputs[i].oninput = function () {
                    document.getElementById("msg1").innerHTML = "";
                    document.getElementById("msg2").innerHTML = "";
                }
            }
        };
        submit_pwd_btn.onclick = function () {
            var flag = true;
            for (let i = 0; i < inputs.length; i++) {
                if (inputs[i].value == "") {
                    flag = false;
                    alert("请填写完整信息！")
                    break;
                }
            }
            if (flag) {
                if (inputs[1].value != inputs[2].value) {
                    document.getElementById("msg2").innerHTML = "两次密码不一致！"
                    inputs[1].value = "";
                    inputs[2].value = "";
                } else {
                    xhr = new XMLHttpRequest();
                    xhr.open("POST", "{% url 'user:account_security' %}", true);
                    xhr.onreadystatechange = function () {
                        response = xhr.responseText
                        if (xhr.readyState == 4 && xhr.status == 200) {
                            if (response == "false") {
                                document.getElementById("msg1").innerHTML = "密码输入错误！";
                                for (let i = 0; i < inputs.length - 1; i++) {
                                    inputs[i].value = ""
                                }
                            } else {
                                alert("修改成功！")
                                window.location = "{% url 'user:account_security' %}";
                            }
                        }
                    };
                    xhr.setRequestHeader('content-type', 'application/x-www-form-urlencoded');
                    xhr.send("old_pwd=" + inputs[0].value + "&new_pwd=" + inputs[1].value)
                }
            }
        }
    </script>
{% endblock %}

templates/user/user_center/address.html
{% extends 'user/user_center/usercenter_base.html' %}
{% block user_center %}
    <style>
        .edit_address {
            width: 500px;
            height: 50px;
            margin: 20px auto 0 0px
        }

        .edit_address span {
            width: 100px;
            height: 30px;
            display: inline-block;
            float: left
        }
    </style>
    <h3 style="margin: 30px auto 0 50px">地址管理</h3>
    <div style="margin: 10px auto 0 50px;">
        <form action="{% url 'user:address' %}" method="POST" class="edit_address" id="edit_address_form">
            <span>当前地址：</span>
            {% if user.direction %}
                <span id="address_span" style="width: 400px">{{ user.direction }}</span><br>
            {% else %}
                <span id="address_span" style="width: 400px">无</span><br>
            {% endif %}
        </form>
        <button style="width: 80px;height: 30px;margin-top: 0px" id="edit_address_btn">编辑</button>
    </div>
    <script>
        var edit_address_btn = document.getElementById("edit_address_btn"),
            edit_address_form = document.getElementById("edit_address_form"),
            address_span = document.getElementById("address_span");
        edit_address_btn.onclick = function () {
            if (edit_address_btn.innerHTML == "编辑") {
                address_span.innerHTML = "<input type=\"text\" " + "value=" + address_span.innerHTML + " name=address" + ">";
                edit_address_btn.innerHTML = "保存";
            } else {
                edit_address_form.submit();
            }
        }
    </script>
{% endblock %}
/>

templates/user/user_center/basic_info.html
{% extends 'user/user_center/usercenter_base.html' %}
{% block user_center %}
    <h3 style="margin: 30px auto 0 50px">基本信息</h3>
    <table class="basic_info_table">
        <tr>
            <td>用户名：</td>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <td>昵称：</td>
            <td>{{ user.nickname }}</td>
        </tr>
        <tr>
            <td>性别：</td>
            <td>{{ user.gender }}</td>
        </tr>
        <tr>
            <td>出生日期：</td>
            <td style="width: 120px">{{ user.birth_date }}</td>
        </tr>
        <tr>
            <td>手机：</td>
            <td style="width: 120px">{{ user.phone }}</td>
        </tr>
        <tr>
            <td>邮箱：</td>
            <td style="width: 120px">{{ user.email }}</td>
        </tr>
    </table>
    <div>
        <button class="basic_info_btn">编辑</button>
    </div>
    <script>
        var basic_info_btn = document.getElementsByClassName("basic_info_btn")[0];
        basic_info_btn.onclick = function () {
            xhr = new XMLHttpRequest();
            xhr.open("GET", "{% url 'user:edit_basic_info' %}", true);
            xhr.onreadystatechange = function () {
                if (xhr.readyState == 4 && xhr.status == 200) {
                    right_content.innerHTML = xhr.responseText;
                }
            };
            xhr.send();
        }
    </script>
{% endblock %}

templates/user/user_center/edit_basic_info.html
<h3 style="margin: 30px auto 0 50px">基本信息</h3>
<form action="{% url 'user:edit_basic_info' %}" method="post">
    <table class="basic_info_table">
        <tr>
            <td>用户名：</td>
            <td><input type="text" name="username" value="{{ user.username }}"></td>
        </tr>
        <tr>
            <td>昵称：</td>
            <td>
                {% if user.nickname %}
                    <input type="text" name="nickname" value="{{ user.nickname }}">
                {% else %}
                    <input type="text" name="nickname" value="">
                {% endif %}
            </td>
        </tr>
        <tr>
            <td>性别：</td>
            <td>
                <select name="gender" id="">
                    <option value="男">男</option>
                    <option value="女">女</option>
                    <option value="其他">其他</option>
                </select>
            </td>
        </tr>
        <tr>
            <td>出生日期：</td>
            <td><input type="date" name="birth_date" id="birth_date" value="{{ user.birth_date }}"></td>
        </tr>
        <tr>
            <td>手机：</td>
            <td><input type="text" name="phone" id="phone" value="{{ user.phone }}"></td>
        </tr>
        <tr>
            <td>邮箱：</td>
            <td><input type="text" name="email" id="email" value="{{ user.email }}"></td>
        </tr>
    </table>
    <div>
        <input type="submit" class="basic_info_btn" value="保存"/>
    </div>
</form>

templates/user/user_center/usercenter_base.html
{% extends 'user/base.html' %}
{% block title %}个人中心{% endblock %}
{% block content %}
    <style>
        .left_bar {
            width: 20%;
            min-height: 350px;
            float: left;
        }

        .right_content {
            width: 79%;
            min-height: 330px;
            float: left;
            border: solid 1px #dedede;
            margin: 0 0 30px 0;
        }

        .left_bar h2 {
            text-align: center;
            border-bottom: solid 1px #3685f1;
            width: 200px;
            margin: 30px auto 5px
        }

        .left_bar ul {
            padding-left: 0;
            width: 200px;
            margin: 0 auto;
            text-align: center;
        }

        .left_bar ul li {
            margin: 10px;
            font: 20px bold 微软雅黑;
            height: 40px;
            line-height: 40px;
        }

        .left_bar ul li:hover {
            background-color: #428bca;
            color: white;
            cursor: pointer;
        }

        .basic_info_table {
            margin: 5px auto auto 50px;
            border-collapse: collapse
        }

        .basic_info_table tr td {
            height: 40px;
            width: 100px;
        }

        .basic_info_btn {
            width: 80px;
            height: 30px;
            margin: 20px 50px;
        }
    </style>
    <div class="left_bar">
        <h2>个人中心</h2>
        <ul>
            <li id="basic_info" class="left_li">基本信息</li>
            <li id="account_security" class="left_li">账户与安全</li>
            <li id="address" class="left_li">地址管理</li>
        </ul>
    </div>
    <div class="right_content">
        {% block user_center %}
        {% endblock %}
    </div>
    <script>
        var items = document.getElementsByClassName("left_li"),
            right_content = document.getElementsByClassName("right_content")[0];
        var xhr = null;
        var user_urls = new Array("{% url 'user:basic_info' %}", "{% url 'user:account_security' %}", "{% url 'user:address' %}")
        for (let i = 0; i < items.length; i++) {
            items[i].onclick = function () {
                window.location = user_urls[i];
            }
        }

    </script>
{% endblock %}