campus_supermarket/urls.py
import django
from django.conf.urls import url, include

from campus_supermarket import settings
from goods import views

urlpatterns = [
    url(r'^admin/', include('cs_admin.urls', namespace='cs_admin')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^index/', views.index),
    url(r'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT}),

]

goods/urls.py
from django.conf.urls import url
from goods import views

app_name = 'goods'

urlpatterns = [
    url(r'^index/', views.index, name='index'),
    url(r'^show/', views.show, name='show'),
    url(r'^goods_detail/', views.goods_detail, name='goods_detail'),
]

order/urls.py
from django.conf.urls import url

from order import views

app_name = 'order'

urlpatterns = [
    url(r'list_order/', views.list_order, name='list_order'),
    url(r'list_cart/', views.list_cart, name='list_cart'),
    url(r'^add_cart/', views.add_cart, name='add_cart'),
    url(r'^delete_cart/', views.delete_cart, name='delete_cart'),
    url(r'^add_order/', views.add_order, name='add_order'),
]

user/urls.py
from django.conf.urls import url

from user import views

app_name = 'user'
urlpatterns = [
    # 注册
    url(r'^register/', views.register, name='register'),
    # 登陆
    url(r'^login/', views.login, name='login'),
    # 退出
    url(r'^logout/', views.logout, name='logout'),
    # 编辑
    url(r'^basic_info/$', views.basic_info, name='basic_info'),
    url(r'^edit_basic_info/$', views.edit_basic_info, name='edit_basic_info'),
    url(r'^account_security/$', views.account_security, name='account_security'),
    url(r'^address/$', views.address, name='address'),

]

goods/models.py
from django.db import models

# Create your models here.


class GoodsInfo(models.Model):
    goods_name = models.CharField(max_length=20)  # 商品名称
    goods_img = models.ImageField(max_length=100, upload_to='goods')  # 商品图片
    goods_num = models.IntegerField()  # 商品货号
    goods_price = models.FloatField(default=0)  # 商品价格
    goods_unit = models.CharField(max_length=20, default='500g')  # 商品单位
    goods_manufacturer = models.CharField(max_length=50)  # 生产厂家
    goods_repertory = models.IntegerField()  # 商品库存
    cag = models.ForeignKey('GoodsCategory', on_delete=models.CASCADE)

    class Meta:
        db_table = 'goodsinfo'


class GoodsCategory(models.Model):
    cag_name = models.CharField(max_length=100)
    cag_img = models.ImageField(upload_to='cag')

    class Meta:
        db_table = 'goods_category'

user/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    username = models.CharField(max_length=32, unique=True)      # 用户名
    nickname = models.CharField(max_length=32)  # 昵称
    password = models.CharField(max_length=256)                  # 密码
    email = models.CharField(max_length=64, unique=True)         # 邮箱
    gender = models.CharField(max_length=10)  # 性别
    birth_date = models.DateField(max_length=32)  # 出生日期
    phone = models.CharField(max_length=11, default='')          # 收件人电话
    direction = models.CharField(max_length=100, default='')     # 收货地址

    class Meta:
        db_table = 'user'

goods/views.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse

from campus_supermarket.settings import MEDIA_URL
from goods.models import GoodsInfo, GoodsCategory
from user.models import User


class Cag_Goods:
    def __init__(self, cag, goods_list):
        self.cag = cag
        self.goods_list = goods_list


def index(request):
    user = None
    try:
        user = User.objects.get(id=request.session['user_id'])
    except:
        pass
    cag_list = GoodsCategory.objects.all()
    cag_goods_list = []
    for cag in cag_list:
        goods_list = GoodsInfo.objects.filter(cag_id=cag.id)[:4]
        g = Cag_Goods(cag, goods_list)
        cag_goods_list.append(g)
    return render(request, 'user/index.html', {'user': user, 'cag_goods_list': cag_goods_list,  'MEDIA_URL': MEDIA_URL})


def show(request):
    content = request.GET.get('content')
    if content:
        request.session["last_search"] = content
    else:
        content = request.session["last_search"]
    page = request.GET.get('page_num')
    goods_list = GoodsInfo.objects.filter(Q(goods_name__icontains=content)
                                          | Q(goods_manufacturer__icontains=content)
                                          )
    num = len(goods_list)
    p = Paginator(goods_list, 10)
    try:
        goods_list = p.page(page)
    except PageNotAnInteger:
        goods_list = p.page(1)
    except EmptyPage:
        goods_list = p.page(p.num_pages)
    user = None
    try:
        user = User.objects.get(id=request.session.get('user_id'))
    except:
        pass
    return render(request, 'user/show.html', {'goods_list': goods_list, 'user': user, 'num': num, 'MEDIA_URL': MEDIA_URL})


def goods_detail(request):
    user_id = request.session.get("user_id")
    user = User.objects.get(id=user_id)
    goods_id = request.GET.get('gid')
    goods = GoodsInfo.objects.get(id=goods_id)
    goods.cag_name = GoodsCategory.objects.get(id=goods.cag_id).cag_name
    return render(request, 'user/goods/goods_detail.html', {'goods': goods, "user": user, "MEDIA_URL": MEDIA_URL})

user/views.py
from datetime import datetime, timedelta

from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from user.models import User
# Create your views here.


def login(request):
    if request.method == 'GET':
        return render(request, 'user/login.html')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('pwd')
        print(username)
        print(password)
        # 验证用户是否注册
        if User.objects.filter(username=username).exists():
            user = User.objects.get(username=username)
            # 验证密码是否正确
            if password == user.password:
                request.session['user_id'] = user.id
                return HttpResponse("登录成功！")
            else:
                return HttpResponse("用户名或密码错误！")
        else:
            return HttpResponse("用户名不存在,请注册后再登陆!")


def logout(request):
    try:
        del request.session['user_id']
    except:
        pass
    finally:
        return redirect(reverse('user:login'))


def register(request):
    if request.method == 'GET':
        return render(request, 'user/register.html')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('pwd')
        email = request.POST.get("email")
        if User.objects.filter(username=username):
            return HttpResponse("用户名已被占用！")
        if User.objects.filter(email=email):
            return HttpResponse("邮箱已被占用！")
        User.objects.create(username=username, password=password, email=email)
        return HttpResponse("注册成功！请返回登录")


def basic_info(request):
    if request.method == 'GET':
        user = User.objects.get(id=request.session.get('user_id'))
        return render(request, 'user/user_center/basic_info.html', {'user': user})
    elif request.method == 'POST':
        pass


def edit_basic_info(request):
    user = User.objects.get(id=request.session.get('user_id'))
    if request.method == "GET":
        return render(request, 'user/user_center/edit_basic_info.html', {'user': user})
    elif request.method == "POST":
        user.username = request.POST.get("username") if request.POST.get("username") else user.username
        user.nickname = request.POST.get("nickname") if request.POST.get("nickname") else user.nickname
        user.gender = request.POST.get("gender") if request.POST.get("gender") else user.gender
        user.birth_date = request.POST.get("birth_date") if request.POST.get("birth_date") else user.birth_date
        user.phone = request.POST.get("phone") if request.POST.get("phone") else user.phone
        user.email = request.POST.get("email") if request.POST.get("email") else user.email
        user.save()
        redirect(reverse('user:basic_info'))
        return render(request, 'user/user_center/basic_info.html', {'user': user})


def account_security(request):
    user = User.objects.get(id=request.session.get('user_id'))
    if request.method == 'GET':
        return render(request, 'user/user_center/account_security.html', {'user': user})
    elif request.method == 'POST':
        old_pwd = request.POST.get("old_pwd")
        if old_pwd != user.password:
            return HttpResponse("false")
        else:
            user.password = request.POST.get("new_pwd")
            user.save()
            return render(request, 'user/user_center/account_security.html', {'user': user})


def address(request):
    user = User.objects.get(id=request.session.get('user_id'))
    if request.method == 'GET':
        return render(request, 'user/user_center/address.html', {'user': user})
    elif request.method == 'POST':
        user.direction = request.POST.get("address");
        user.save()
        return render(request, 'user/user_center/address.html', {'user': user})

templates/user/goods/add_order.html
{% extends 'user/base.html' %}
{% block title %}生产订单{% endblock %}
{% block content %}
    <style>
        table{border:1px;border-collapse: collapse;margin: 0 auto;}
        th{height: 40px;line-height: 40px;text-align: center}
        td{height: 40px;line-height: 40px;width: 120px;text-align: center}
        h1{font-size: 16px;margin-left: 190px}
        #end{width: 150px;height: 61px;border:0px;background-color: #ff3d3d;font:30px bold 微软雅黑;float: right;
            color: #FFFFFF;text-align: center;margin-bottom: 20px}

        #total_pay, #buy_num {
            font: 40px bold 微软雅黑;
            float: right;
            color: #ff1d2b;
            line-height: 61px;
        }
        .bottom{background-color: #fff4e8;height: 61px;line-height: 61px;margin: 10px auto;width: 1000px;}
        .bottom_right{float: right;padding: 0px 7px;bottom: 10px;}
    </style>
        <div style="min-height: 240px;margin-top: 40px">
            <table id="table" border="1" >
                <tr>
                    <th>商品图片</th>
                    <th>商品名称</th>
                    <th>商品价格</th>
                    <th>购买数量</th>
                    <th>小计</th>
                </tr>
                {% for goods in goods_list %}
                    <tr class="goods_item">
                        <td><img src="{{ MEDIA_URL}}{{goods.goods_img}}" alt="商品图片" style="max-width: 100px;max-height: 75px"></td>
                        <td>{{ goods.goods_name }}</td>
                        <td>{{ goods.goods_price }} / {{ goods.goods_unit }}</td>
                        <td>{{ goods.num }}</td>
                        <td>{{ goods.pay }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <form action="{% url "order:add_order" %}" id="form3" method="post" style="display: none">
            <input type="text" name="text" style="display: none" value="{{ json }}">
            <input type="text" name="status" value="1">
        </form>
            <div class="bottom">
                <button id="end" onclick="final_submit()"> 提交订单 </button>
                <span class="bottom_right">合计：¥<label id="total_pay" style="padding-right: 20px">{{ total_pay }}</label></span>
                <span class="bottom_right">件商品</span><label id="buy_num">{{ count }}</label><span class="bottom_right">共计</span>
            </div>
    <script>
        function final_submit() {
            let form3 = document.getElementById("form3");
            form3.submit();
        }
    </script>
{% endblock %}

templates/user/goods/goods_detail.html
{% extends 'user/base.html' %}
{% block title %}商品详情{% endblock %}
{% block content %}
    <style>
        #form2 td{margin: 50px 0;padding: 9px 0;}

        .optr {
            float: left;
            height: 20px;
            width: 25px
        }
    </style>
    <div>
        <img src="{{ MEDIA_URL}}{{goods.goods_img}}"  alt="商品图片" style="float: left;max-width: 400px;max-height: 300px;margin-left: 200px">
    </div>
    <div style="margin: 30px 0 0 400px;width: 600px;">
        <form action="{% url 'order:add_cart' %}" method="GET" id="form2">
            <table style="margin: 0 auto;font-size: 20px;">
                <tr>
                    <td>商品名称：</td>
                    <td>{{ goods.goods_name }}</td>
                </tr>
                <tr>
                    <td>生产厂家：</td>
                    <td> {{ goods.goods_manufacturer }}</td>
                </tr>
                <tr>
                    <td>价格：</td>
                    <td>{{ goods.goods_price }} / {{ goods.goods_unit }}</td>
                </tr>
                <tr>
                    <td>库存：</td>
                    <td id="left">{{ goods.goods_repertory }}</td>
                </tr>
                <tr>
                    <td>商品分类：</td>
                    <td>{{ goods.cag_name }}</td>
                </tr>
                <tr>
                    <td>购买数量：</td>
                    <td>
                        <div style="width: 80px;height: 50px;">
                            <input name="num" id="buy_num" type="text" value="1" onkeyup=""
                                   style="border: solid 1px #D9EDF7;height: 36px;width:36px;float: left;text-align: center"/>
                            <button type="button" class="optr">+</button>
                            <button type="button" class="optr">-</button>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <span style="display: none"><input name="gid" type="text" value="{{ goods.id }}"/></span>
                        <input type="button"  id="btn" style="height: 30px;padding: 0 20px;" value="加入购物车" />
                    </td>
                </tr>
            </table>
        </form>
    </div>
    <script>
        var btn = document.getElementById("btn"),
            num = document.getElementById("buy_num"),
            left = document.getElementById("left"),
            form2 = document.getElementById("form2"),
            buy_num = document.getElementById("buy_num"),
            optrs = document.getElementsByClassName("optr");
        optrs[0].onclick = function () {
            buy_num.value = String(parseInt(buy_num.value) + 1);
        };
        optrs[1].onclick = function () {
            let val = parseInt(buy_num.value);
            if (val > 1) {
                buy_num.value = String(val - 1);
            }
        };
        buy_num.onkeyup = function () {
            let val = buy_num.value.replace(/[^1234567890]+/g, '');
            if (parseInt(val) != 0) {
                buy_num.value = val;

            } else {
                buy_num.value = "1";
            }
        };
        btn.onclick = function () {
            if (num.value == "") {
                alert("请填写购买数量！")
            } else if (parseInt(num.value) > parseInt(left.innerHTML)) {
                alert("对不起，库存不足！请减少购买数量或待货源充足时再购买")
            }
            else{
                form2.submit();
            }
        }
    </script>
{% endblock %}

templates/user/goods/list_cart.html
{% extends 'user/base.html' %}
{% block title %}我的购物车{% endblock %}
{% block content %}
    <style>
        table{border-collapse: collapse;margin: 0 auto;}
        th,td{height: 40px;line-height: 40px;width: 120px;text-align: center;}
        th{border-bottom: solid 1px #c9c9c9;}
        h1{font-size: 16px;margin-left: 140px}
        #end{width: 120px;height: 60px;line-height:60px;iborder:0px;background-color: #ff3d3d;font:30px bold 微软雅黑;float: right;
            color: #e9f0d8;text-align: center;padding: auto;}
        #total_pay, #total_num{font: 40px bold 微软雅黑;float: right;color: #ff1d2b;line-height: 61px;}
        .bottom{background-color: #fff4e8;height: 61px;line-height: 61px;margin: 10px auto;width: 1000px}
        .bottom_right{float: right;padding: 0px 7px;bottom: 10px;}
    </style>
    {% if num != 0 %}
        <div style="margin: 30px auto;min-height: 240px">
            <table>
            <thead>
            <tr>
                <th></th>
                <th>商品图片</th>
                <th>商品名称</th>
                <th>商品价格</th>
                <th>单位</th>
                <th>数量</th>
                <th>小计</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for goods in goods_list %}
                <tr>
                    <td><input type="checkbox" class="check_item"  onclick="check(this)"/></td>
                    <td><img src="{{ MEDIA_URL}}{{goods.goods_img}}" alt="商品图片" style="max-width: 100px;max-height: 100px" /></td>
                    <td>{{ goods.goods_name }}</td>
                    <td>{{ goods.goods_price }}</td>
                    <td>{{ goods.goods_unit }}</td>
                    <td><button type="button" onclick="sub(this)">-</button><span>{{ goods.num }}</span><button type="button" onclick="add(this)">+</button></td>
                    <td class="money"></td>
                    <td><a href="{% url 'order:delete_cart' %}/?id={{ goods.item_id }}">删除</a></td>
                </tr>
            {% endfor %}
            </tbody>
            </table>
        </div>
            <div class="bottom">
                <span style="float: left;padding-left: 20px"><input type="checkbox" id="all_box" onclick="checkAllBox(this)"/>全选</span>
                <button  id="end"  onclick="save()">去结算</button>
                <span class="bottom_right">合计：¥<label id="total_pay" style="padding-right: 20px;padding-left: 5px"></label></span>
                <span class="bottom_right">件商品</span><label id="total_num"></label><span class="bottom_right">共</span>
            </div>
    {% else %}
        <div style="height:300px;width:100%;margin: 0 auto;text-align: center;line-height: 300px;">
            您的购物车是空的！
        </div>
    {% endif %}
    <form action="{% url "order:add_order" %}" id="form0" method="post" style="display: none">
        <input type="text" name="text" style="display: none" >
        <input type="text" name="status" value="0">
    </form>
    <script>
        var n = 0;
        var checkboxs = document.getElementsByClassName("check_item"),
            total_num = document.getElementById("total_num"),
            form0 = document.getElementById("form0"),
            money = document.getElementsByClassName("money"),
            all = document.getElementById("all_box"),
            total_pay = document.getElementById("total_pay");
        var url = "{% url "order:add_order" %}?num=";
        var goodsArray = new Array();
        {% for goods in goods_list %}
            goodsArray[n] = {"id": {{ goods.id }}, "price":{{ goods.goods_price }}, "num": {{ goods.num }}, "checked": true};
            n++;
        {% endfor %}
        window.onload=function () {
            all.checked=true;
            let sum = 0;
            for(let i = 0;i<n;i++){
                sum += parseInt(goodsArray[i].num)
                money[i].innerHTML = String(parseFloat(goodsArray[i].price) * parseInt(goodsArray[i].num));
                checkboxs[i].checked=true;
                checkboxs[i].id= String(i);
            }
            get_total_pay();
            total_num.innerHTML = String(sum);

        }
        function sub(that) {
            var text = that.nextElementSibling;
            num = parseInt(text.innerHTML);
            if(num>1){
                text.innerHTML = String(num-1);
                goodsArray[parseInt(that.parentElement.parentElement.firstElementChild.firstElementChild.id)].num = num-1;
                total_num.innerHTML = String(parseInt(total_num.innerHTML)-1)
            }
            sum(that);
            get_total_pay();
        }
        function add(that) {
            var text = that.previousElementSibling;
            num = parseInt(text.innerHTML);
            text.innerHTML = num+1;
            goodsArray[parseInt(that.parentElement.parentElement.firstElementChild.firstElementChild.id)].num = num+1;
            total_num.innerHTML = String(parseInt(total_num.innerHTML)+1)
            sum(that);
            get_total_pay();
        }
        function sum(that) {
            let money = that.parentElement.nextElementSibling,
                price = that.parentElement.previousElementSibling.previousElementSibling.innerHTML,
                num = that.parentElement.children[1];
            price = parseFloat(price);
            num = parseInt(num.innerHTML);
            money.innerHTML = String(parseFloat(String(num * price)));
        }
        function checkAllBox(that) {
            if(that.checked){
                for(let i = 0;i<n;i++){
                    checkboxs[i].checked = true;
                    goodsArray[i].checked = true;
                }
                let sum = 0;
                for(let i = 0;i<n;i++){
                    if(checkboxs[i].checked){
                        sum += parseInt(goodsArray[i].num)
                    }
                }
                total_num.innerHTML = String(sum);
            }
            else{
                for(let i = 0;i<n;i++){
                    checkboxs[i].checked = false;
                    goodsArray[i].checked = false;
                }
                total_num.innerHTML = String(0);
            }
            get_total_pay();
        }
        function check(that) {
            let num = that.parentElement.parentElement.children[5].children[1].innerHTML;
            if(that.checked)
                total_num.innerHTML = String(parseInt(total_num.innerHTML) + parseInt(num));
            else {
                total_num.innerHTML = String(parseInt(total_num.innerHTML) - parseInt(num));
            }

            goodsArray[parseInt(that.id)].checked = that.checked;
            get_total_pay();
            for (let i = 0;i<n;i++){
                if(!checkboxs[i].checked){
                    all.checked=false;
                    return;
                }
            }
            all.checked=true;
        }
        function get_total_pay() {
            let sum = 0;
            for(let i = 0;i<n;i++){
                if(checkboxs[i].checked){
                    sum += parseFloat(money[i].innerHTML);
                }
            }
            total_pay.innerHTML = String(sum);
        }
        function save() {
            let count = 0, t = 0;
            for(let i = 0;i<n;i++){
                if(checkboxs[i].checked){
                    count++;
                    let str = JSON.stringify(goodsArray[i]);
                    localStorage.setItem("goods"+t, str);
                    t++;
                }
            }
            if(count>0) {
                let goods = [];
                for (let i = 0; i < n; i++) {
                    if (checkboxs[i].checked) {
                        goods.push(goodsArray[i]);
                    }
                }
                form0.firstElementChild.value = JSON.stringify(goods);
                form0.submit();
            }
            else{
                alert("您没有选择任何商品！")
            }
        }
    </script>
{% endblock %}

templates/user/goods/list_order.html
{% extends 'user/base.html' %}
{% block title %}我的订单{% endblock %}
{% block content %}
    <style>
        tr{height: 40px;}
    </style>
    {% if order_group %}
        <h2 style="padding-left: 130px">已完成订单：</h2>
        <div style="margin-top: 10px">
            {% for order in order_group %}
                <div style="width:1000px;height:30px;background-color:#d9edf7;font: 16px bold 微软雅黑;margin: 0 auto;">
                    <span>订单号：{{ order.desc.id }} </span>
                    <span style="padding-left: 40px;display: inline-block;height: 30px;line-height: 30px;">下单时间：{{ order.desc.order_date }}</span>
                </div>

                <table border="1" style="border-collapse: collapse;width: 1000px;text-align: center;margin: 5px;margin: 10px auto">
                    <tr>
                        <th>商品图片</th>
                        <th>商品名称</th>
                        <th>商品单价</th>
                        <th>商品数量</th>
                        <th>生产厂家</th>
                        <th>金额</th>
                    </tr>
                    {% for goods in order.goods_list %}
                        <tr>
                            <td><img src="{{ MEDIA_URL}}{{goods.goods_img}}" alt="商品图片" style="max-width: 100px;max-height: 100px" /></td>
                            <td>{{ goods.goods_name }}</td>
                            <td>{{ goods.goods_price }}/{{ goods.goods_unit }}</td>
                            <td>{{ goods.num }}</td>
                            <td>{{ goods.goods_manufacturer }}</td>
                            <td>{{ goods.pay }}</td>
                        </tr>
                    {% endfor %}
                </table>
                <div style="height:30px;padding:5px 0 30px 130px;font: 16px bold 微软雅黑"><strong>合计：</strong><span style="font: 20px bold 微软雅黑;color: red">¥ {{ order.desc.order_total }}</span></div>
            {% endfor %}
        </div>
        <div style="text-align: center;margin: 5px">
            {% if order_group.has_previous %}
                <a href="{% url 'order:list_order' %}?page_num={{ order_group.previous_page_number }}">上一页</a>
            {% endif %}
            {% for i in order_group.paginator.page_range %}
                {% if i == order_group.number %}
                    <a href="{% url 'order:list_order' %}?page_num={{ i }}" style="font-size: 30px;padding: 0 10px">{{ i}}</a>
                {% else %}
                    <a href="{% url 'order:list_order' %}?page_num={{ i }}" style="font-size: 20px;padding: 0 10px">{{ i }}</a>
                {% endif %}
            {% endfor %}
            {% if order_group.has_next %}
                <a href="{% url 'order:list_order' %}?page_num={{ order_group.next_page_number }}">下一页</a>
            {% endif %}
        </div>
    {% else %}
        <div style="height:300px;width:100%;margin: 0 auto;text-align: center;line-height: 300px;">
            暂无历史订单！
        </div>
    {% endif %}
{% endblock %}