campus_supermarket/urls.py
import django
from django.conf.urls import url, include

from campus_supermarket import settings
from goods import views

urlpatterns = [
    url(r'^admin/', include('cs_admin.urls', namespace='cs_admin')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^index/', views.index),
    url(r'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT}),

]

goods/urls.py
from django.conf.urls import url
from goods import views

app_name = 'goods'

urlpatterns = [
    url(r'^index/', views.index, name='index'),
    url(r'^show/', views.show, name='show'),
    url(r'^goods_detail/', views.goods_detail, name='goods_detail'),
]

order/urls.py
from django.conf.urls import url

from order import views

app_name = 'order'

urlpatterns = [
    url(r'list_order/', views.list_order, name='list_order'),
    url(r'list_cart/', views.list_cart, name='list_cart'),
    url(r'^add_cart/', views.add_cart, name='add_cart'),
    url(r'^delete_cart/', views.delete_cart, name='delete_cart'),
    url(r'^add_order/', views.add_order, name='add_order'),
]

user/urls.py
from django.conf.urls import url

from user import views

app_name = 'user'
urlpatterns = [
    # 注册
    url(r'^register/', views.register, name='register'),
    # 登陆
    url(r'^login/', views.login, name='login'),
    # 退出
    url(r'^logout/', views.logout, name='logout'),
    # 编辑
    url(r'^basic_info/$', views.basic_info, name='basic_info'),
    url(r'^edit_basic_info/$', views.edit_basic_info, name='edit_basic_info'),
    url(r'^account_security/$', views.account_security, name='account_security'),
    url(r'^address/$', views.address, name='address'),

]

user/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    username = models.CharField(max_length=32, unique=True)      # 用户名
    nickname = models.CharField(max_length=32)  # 昵称
    password = models.CharField(max_length=256)                  # 密码
    email = models.CharField(max_length=64, unique=True)         # 邮箱
    gender = models.CharField(max_length=10)  # 性别
    birth_date = models.DateField(max_length=32)  # 出生日期
    phone = models.CharField(max_length=11, default='')          # 收件人电话
    direction = models.CharField(max_length=100, default='')     # 收货地址

    class Meta:
        db_table = 'user'

user/views.py
from datetime import datetime, timedelta

from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from user.models import User
# Create your views here.


def login(request):
    if request.method == 'GET':
        return render(request, 'user/login.html')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('pwd')
        print(username)
        print(password)
        # 验证用户是否注册
        if User.objects.filter(username=username).exists():
            user = User.objects.get(username=username)
            # 验证密码是否正确
            if password == user.password:
                request.session['user_id'] = user.id
                return HttpResponse("登录成功！")
            else:
                return HttpResponse("用户名或密码错误！")
        else:
            return HttpResponse("用户名不存在,请注册后再登陆!")


def logout(request):
    try:
        del request.session['user_id']
    except:
        pass
    finally:
        return redirect(reverse('user:login'))


def register(request):
    if request.method == 'GET':
        return render(request, 'user/register.html')
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('pwd')
        email = request.POST.get("email")
        if User.objects.filter(username=username):
            return HttpResponse("用户名已被占用！")
        if User.objects.filter(email=email):
            return HttpResponse("邮箱已被占用！")
        User.objects.create(username=username, password=password, email=email)
        return HttpResponse("注册成功！请返回登录")


def basic_info(request):
    if request.method == 'GET':
        user = User.objects.get(id=request.session.get('user_id'))
        return render(request, 'user/user_center/basic_info.html', {'user': user})
    elif request.method == 'POST':
        pass


def edit_basic_info(request):
    user = User.objects.get(id=request.session.get('user_id'))
    if request.method == "GET":
        return render(request, 'user/user_center/edit_basic_info.html', {'user': user})
    elif request.method == "POST":
        user.username = request.POST.get("username") if request.POST.get("username") else user.username
        user.nickname = request.POST.get("nickname") if request.POST.get("nickname") else user.nickname
        user.gender = request.POST.get("gender") if request.POST.get("gender") else user.gender
        user.birth_date = request.POST.get("birth_date") if request.POST.get("birth_date") else user.birth_date
        user.phone = request.POST.get("phone") if request.POST.get("phone") else user.phone
        user.email = request.POST.get("email") if request.POST.get("email") else user.email
        user.save()
        redirect(reverse('user:basic_info'))
        return render(request, 'user/user_center/basic_info.html', {'user': user})


def account_security(request):
    user = User.objects.get(id=request.session.get('user_id'))
    if request.method == 'GET':
        return render(request, 'user/user_center/account_security.html', {'user': user})
    elif request.method == 'POST':
        old_pwd = request.POST.get("old_pwd")
        if old_pwd != user.password:
            return HttpResponse("false")
        else:
            user.password = request.POST.get("new_pwd")
            user.save()
            return render(request, 'user/user_center/account_security.html', {'user': user})


def address(request):
    user = User.objects.get(id=request.session.get('user_id'))
    if request.method == 'GET':
        return render(request, 'user/user_center/address.html', {'user': user})
    elif request.method == 'POST':
        user.direction = request.POST.get("address");
        user.save()
        return render(request, 'user/user_center/address.html', {'user': user})

templates/user/add_order.html
{% extends 'user/base.html' %}
{% block title %}生产订单{% endblock %}
{% block content %}
    <style>
        table{border:1px;border-collapse: collapse;margin: 0 auto;}
        th{height: 40px;line-height: 40px;text-align: center}
        td{height: 40px;line-height: 40px;width: 120px;text-align: center}
        h1{font-size: 16px;margin-left: 190px}
        #end{width: 150px;height: 61px;border:0px;background-color: #ff3d3d;font:30px bold 微软雅黑;float: right;
            color: #FFFFFF;text-align: center;margin-bottom: 20px}
        #total_pay, #num{font: 40px bold 微软雅黑;float: right;color: #ff1d2b;line-height: 61px;}
        .bottom{background-color: #fff4e8;height: 61px;line-height: 61px;margin: 10px auto;width: 1000px;}
        .bottom_right{float: right;padding: 0px 7px;bottom: 10px;}
    </style>
        <div style="min-height: 240px;margin-top: 40px">
            <table id="table" border="1" >
                <tr>
                    <th>商品图片</th>
                    <th>商品名称</th>
                    <th>商品价格</th>
                    <th>购买数量</th>
                    <th>小计</th>
                </tr>
                {% for goods in goods_list %}
                    <tr class="goods_item">
                        <td><img src="{{ MEDIA_URL}}{{goods.goods_img}}" alt="商品图片" style="max-width: 100px;max-height: 75px"></td>
                        <td>{{ goods.goods_name }}</td>
                        <td>{{ goods.goods_price }} / {{ goods.goods_unit }}</td>
                        <td>{{ goods.num }}</td>
                        <td>{{ goods.pay }}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <form action="{% url "order:add_order" %}" id="form3" method="post" style="display: none">
            <input type="text" name="text" style="display: none" value="{{ json }}">
            <input type="text" name="status" value="1">
        </form>
            <div class="bottom">
                <button id="end" onclick="final_submit()"> 提交订单 </button>
                <span class="bottom_right">合计：¥<label id="total_pay" style="padding-right: 20px">{{ total_pay }}</label></span>
                <span class="bottom_right">件商品</span><label id="num">{{ count }}</label><span class="bottom_right">共计</span>
            </div>
    <script>
        function final_submit() {
            let form3 = document.getElementById("form3");
            form3.submit();
        }
    </script>
{% endblock %}

templates/user/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <title>{% block title%}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/user.css' %}">
    <link rel="stylesheet" href="{% static 'css/user_index.css' %}">
</head>
<body>
    <div class="header">
        <img class="logo" src="/static/images/logo.png" alt="logo">
        <div class="search">
            <form action="{% url 'goods:show' %}" id="form1">
                <input type="text" class="search_input" name="content" placeholder="搜索商品..."/>
                <button class="search_btn" type="button">搜索</button>
            </form>
        </div>
        <div id="top_right">
            {% if user.id %}
                您好，{{ user.username }}
                <span class="sep">|</span>
                <a href="{% url 'user:logout' %}">退出</a>
            {% else %}
                您好，访客！
                <span class="sep">|</span>
                <a href="{% url 'user:login' %}">登录</a>
                <span class="sep">|</span>
                <a href="{% url 'user:register' %}">注册</a>
            {% endif %}
        </div>
	</div>
    <div class="nav_div">
        <ul class="nav">
            <li class="nav_item">首页</li>
            <li class="nav_item">我的购物车</li>
            <li class="nav_item">我的订单</li>
            <li class="nav_item">个人中心</li>
        </ul>
    </div>
    </div>
    <div class="content" style="min-height: 60%">
        {% block content %}
        {% endblock %}
    </div>
    <div class="footer">
        <div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2019 南京校园超市技术有限公司 All Rights Reserved</p>
		<p>电话：025-****888    宁ICP备*******8号</p>
    </div>
    <script>
        var nav_items = document.getElementsByClassName("nav_item");
        var logo = document.getElementsByClassName("logo")[0];
        var urls = new Array("{% url 'goods:index' %}", "{% url 'order:list_cart' %}",
            "{% url 'order:list_order' %}", "{% url 'user:basic_info' %}");
        var btn = document.getElementsByClassName("search_btn")[0],
            text = document.getElementsByClassName("search_input")[0],
            form1 = document.getElementById("form1"),
            content = document.getElementsByClassName("content")[0];
        var xhr = null;
        for (let i = 0; i < nav_items.length; i++) {
            if(i == 0) {
                nav_items[i].onclick = function () {
                    window.location = urls[i];
                }
            }else{
                nav_items[i].onclick = function () {
                    {% if user.id %}
                        window.location = urls[i];
                    {% else %}
                        alert("亲，请先登录哦！");
                        window.location = "{% url 'user:login' %}";
                    {% endif %}
                }
            }
        }
        logo.onclick = function () {
            location = urls[0];
        };
        btn.onclick = function () {
            if(text.value != ""){
                form1.submit();
            }
        }
    </script>
</body>
</html>

templates/user/goods_detail.html
{% extends 'user/base.html' %}
{% block title %}商品详情{% endblock %}
{% block content %}
    <style>
        #form2 td{margin: 50px 0;padding: 9px 0;}
    </style>
    <div>
        <img src="{{ MEDIA_URL}}{{goods.goods_img}}"  alt="商品图片" style="float: left;max-width: 400px;max-height: 300px;margin-left: 200px">
    </div>
    <div style="margin: 30px 0 0 400px;width: 600px;">
        <form action="{% url 'order:add_cart' %}" method="GET" id="form2">
            <table style="margin: 0 auto;font-size: 20px;">
                <tr>
                    <td>商品名称：</td>
                    <td>{{ goods.goods_name }}</td>
                </tr>
                <tr>
                    <td>生产厂家：</td>
                    <td> {{ goods.goods_manufacturer }}</td>
                </tr>
                <tr>
                    <td>价格：</td>
                    <td>{{ goods.goods_price }} / {{ goods.goods_unit }}</td>
                </tr>
                <tr>
                    <td>库存：</td>
                    <td id="left">{{ goods.goods_repertory }}</td>
                </tr>
                <tr>
                    <td>商品分类：</td>
                    <td>{{ goods.cag_id }}</td>
                </tr>
                <tr>
                    <td>购买数量：</td>
                    <td><input name="num" id="num" type="text" style="border: solid 1px #D9EDF7;height: 25px"/></td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <span style="display: none"><input name="gid" type="text" value="{{ goods.id }}"/></span>
                        <input type="button"  id="btn" style="height: 30px;padding: 0 20px;" value="加入购物车" />
                    </td>
                </tr>
            </table>
        </form>
    </div>
    <script>
        var btn = document.getElementById("btn"),
            num = document.getElementById("num"),
            left = document.getElementById("left"),
            form2 = document.getElementById("form2");
        btn.onclick = function () {
            if(parseInt(num.value) > parseInt(left.innerHTML)){
                alert("对不起，库存不足！请减少购买数量或待货源充足时再购买")
            }
            else{
                form2.submit();
            }
        }
    </script>
{% endblock %}

templates/user/index.html
{% extends 'user/base.html' %}
{% load static %}
{% block title %}校园超市-首页{% endblock %}
{% block content %}
    <div class="left_chunk">
        <div style="font-size: 30px;text-align: center;margin:5px 50px 5px auto;width:200px;border-bottom: 1px solid #3685f1">全部分类</div>
        <ul>
            {% for cag_goods in cag_goods_list %}
                <a href="#{{ cag_goods.cag.cag_name }}">
                    <li style="line-height: 40px">
                        <div style="margin: 0 auto;height: 40px;width: 120px;">
                            <img alt="" style="height: 30px;width: 30px;float: left;padding-top: 3px" class="cag_img">
                            <span style="float: left;padding-left: 10px">{{ cag_goods.cag.cag_name }}</span>
                        </div>
                    </li>
                </a>
            {% endfor %}
        </ul>
    </div>
    <div class="right_chunk">
        <div class="slides">
            <ul class="slides_ul">
                <li><img src="/static/images/slide1.jpg" alt="图片1"></li>
                <li><img src="/static/images/slide2.jpg" alt="图片2"></li>
                <li><img src="/static/images/slide3.jpg" alt="图片3"></li>
                <li><img src="/static/images/slide4.jpg" alt="图片4"></li>
            </ul>
            <ul class="slides_bottom">
                <li style="background-color: blue"></li>
                <li style="background-color: #C8C8C8"></li>
                <li style="background-color: #C8C8C8"></li>
                <li style="background-color: #C8C8C8"></li>
            </ul>
        </div>
    </div>
    <div class="main">
        {% for cag_goods in cag_goods_list %}
            <div class="sub_item" id="{{ cag_goods.cag.cag_name }}">
                <img src="{{ MEDIA_URL}}{{cag_goods.cag.cag_img}}" alt="分类图片" style="width: 40px;height: 40px;float: left;margin-right: 40px;margin-left: 10px;">
                <span>{{ cag_goods.cag.cag_name }}</span>
                <span style="float: right;font: 16px bold 微软雅黑;line-height: 41px;margin-right: 30px;"><a href="#">更多>></a></span>
            </div>
            <div class="cag_goods">
                {% for goods in cag_goods.goods_list %}
                    <div class="goods_info">
                        <div style="height: 180px;width: 200px">
                            <a href="{% url 'goods:goods_detail' %}?gid={{ goods.id }}"><img src="{{ MEDIA_URL}}{{goods.goods_img}}" alt="商品图片" ></a><br>
                        </div>
                        <div style="height: 20px;text-align: center;color: red;margin: 5px">¥ {{ goods.goods_price }} / {{ goods.goods_unit }}</div>
                        <div style="text-align: center;font: 22px bold 微软雅黑">{{ goods.goods_name }}</div>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
    <script>
        var slides_ul = document.getElementsByClassName("slides_ul")[0];
        var k = 0, count = slides_ul.children.length;
        var left = slides_ul.offsetLeft, width = slides_ul.firstElementChild.offsetWidth;
        var blues = document.getElementsByClassName("slides_bottom")[0];
        var t = setInterval(change,3000);
        var cag_imgs = document.getElementsByClassName("cag_img");
        var cag_names = new Array("零食", "水果", "文具", "生活用品", "电器", "饮料");
        window.onload = init;
        function init() {
            for (let i = 0; i < 6; i++) {
                cag_imgs[i].src = "/static/images/" + cag_names[i] + ".png";
            }
            for(let i = 0;i<count;i++){
                blues.children[i].onmouseenter = function () {
                    slides_ul.style.left = left - i * width +"px";
                    blues.children[i].style.backgroundColor = "blue";
                    for(let j = 0;j<count;j++){
                        if(i != j){
                            blues.children[j].style.backgroundColor = "#C8C8C8";
                        }
                    }
                    k = i;
                }
            }
            blues.onmouseenter = function () {
                clearInterval(t);
            };
            blues.onmouseleave = function () {
                t = setInterval(change,3000);
            }
        }
        function change() {
            slides_ul.style.left = left - k * width + "px";
            blues.children[k].style.backgroundColor = "blue";
            let pre = (k-1+count)%count;
            blues.children[pre].style.backgroundColor = "#C8C8C8";
            k = (k+1)%count;
        }
    </script>
{% endblock %}

templates/user/login.html
<html>
<head>
    <title>校园超市-登录</title>
    <style>
        .login_body {
            height: 460px;
            width: 500px;
            margin: 60px auto;
            border: solid 1px #e1e1e2;
        }

        .login_body div {
            width: 50%;
            margin: 20px auto
        }

        .login_body div label {
            height: 30px;
            line-height: 30px;
            width: 60px;
            display: inline-block
        }

        .login_body div input {
            height: 30px;
            width: 160px
        }

        .login_body button {
            width: 100px;
            height: 30px;
            margin-left: 185px;
            margin-bottom: 20px
        }

        a {
            text-decoration: none;
            color: #3685f1;
            margin-left: 185px;
        }
    </style>
</head>
<body>
<form action="" method="POST">
    <div class="login_body">
        <div style="width: 500px;height: 200px"><img src="/static/images/logo.png" alt="logo"
                                                     style="width: 500px;height: 200px;"></div>
        <div style="width: 120px;margin: -20px auto 10px auto;font-size: 20px"><strong>用户登录</strong></div>
        <div><label for="username" style="">用户名:</label><input type="text" name="username" id="username"/></div>
        <div><label for="pwd">密码:</label><input type="text" name="pwd" id="pwd"/></div>
        <button type="button" id="user_login_btn">登录</button>
        <br>
        <a href="{% url 'user:register' %}">没有账号？立即注册>></a>
    </div>
</form>
<script>
    var user_login_btn = document.getElementById("user_login_btn"),
        username = document.getElementById("username"),
        pwd = document.getElementById("pwd");
    var xhr = null;
    user_login_btn.onclick = function () {
        if (username.value == "" || pwd.value == "") {
            alert("用户名或密码不能为空！")
        } else {
            xhr = new XMLHttpRequest();
            xhr.open("POST", "{% url 'user:login' %}", true);
            xhr.onreadystatechange = function () {
                if (xhr.readyState == 4 && xhr.status == 200) {
                    let ans = xhr.responseText;
                    alert(ans);
                    if (ans == "登录成功！") {
                        window.location = "{% url 'goods:index' %}"
                    }
                }
            };
            xhr.setRequestHeader('content-type', 'application/x-www-form-urlencoded');
            xhr.send("username=" + username.value + "&pwd=" + pwd.value)
        }
    }
</script>
</body>
</html>

templates/user/register.html
<html>
<head>
    <title>校园超市-注册</title>
    <style>
        .register_body {
            height: 525px;
            width: 500px;
            margin: 40px auto;
            border: solid 1px #e1e1e2;
        }

        .register_body div {
            width: 50%;
            margin: 20px auto
        }

        .register_body div label {
            height: 30px;
            line-height: 30px;
            width: 70px;
            display: inline-block
        }

        .register_body div input {
            height: 30px;
            width: 160px
        }

        .register_body button {
            width: 100px;
            height: 30px;
            margin-left: 196px;
            margin-bottom: 20px
        }

        a {
            text-decoration: none;
            color: #3685f1;
            margin-left: 185px;
        }
    </style>
</head>
<body>
<form action="" method="POST">
    <div class="register_body">
        <div style="width: 500px;height: 200px"><img src="/static/images/logo.png" alt="logo"
                                                     style="width: 500px;height: 200px;"></div>
        <div><label for="username" style="">用户名:</label><input type="text" name="username" id="username"/></div>
        <div><label for="pwd">密码:</label><input type="password" name="pwd" id="pwd"/></div>
        <div><label for="pwd_c">确认密码:</label><input type="password" name="pwd_c" id="pwd_c"/></div>
        <div><label for="email">邮箱:</label><input type="text" name="email" id="email"/></div>
        <button type="button" id="user_register_btn">注册</button>
        <br>
        <a href="{% url 'user:login' %}">已有账号？去登录>></a>
    </div>
</form>
<script>
    var user_register_btn = document.getElementById("user_register_btn"),
        username = document.getElementById("username"),
        pwd = document.getElementById("pwd"),
        pwd_c = document.getElementById("pwd_c"),
        email = document.getElementById("email");
    var xhr = null;
    user_register_btn.onclick = function () {
        if (username.value == "" || pwd.value == "" || pwd_c.value == "" || email.value == "") {
            alert("请将信息填写完整！")
        } else if (pwd.value != pwd_c.value) {
            alert("两次密码输入不一致！")
        } else {
            xhr = new XMLHttpRequest();
            xhr.open("POST", "{% url 'user:register' %}", true);
            xhr.onreadystatechange = function () {
                if (xhr.readyState == 4 && xhr.status == 200) {
                    let ans = xhr.responseText;
                    alert(ans);
                    if (ans == "注册成功！请返回登录") {
                        window.location = "{% url 'user:login' %}"
                    }
                }
            };
            xhr.setRequestHeader('content-type', 'application/x-www-form-urlencoded');
            xhr.send("username=" + username.value + "&pwd=" + pwd.value + "&email=" + email.value);
            }
    }
</script>
</body>
</html>

templates/user/show.html
{% extends 'user/base.html' %}
{% block title %}搜索商品{% endblock %}
{% block content %}
    <style>
        table{border-collapse: collapse;margin: 0 auto;}
        th,td{height: 40px;line-height: 40px;width: 120px;text-align: center;border: solid 1px #D9EDF7;}
        h1{font-size: 16px;margin-left: 200px}
    </style>
    <div style="margin: 0 auto">
        <h1>为您找到{{ num }}件商品：</h1>
        <table border="1">
        <tr>
            <th>商品图片</th>
            <th>商品名</th>
            <th>价格</th>
            <th>库存</th>
            <th>生产商</th>
            <th>分类</th>
            <th>操作</th>
        </tr>
        {% for goods in goods_list %}
            <tr>
                <td>
                    <a href="{% url 'goods:goods_detail' %}?gid={{ goods.id }}">
                        <img src="{{ MEDIA_URL}}{{goods.goods_img}}" alt="商品图片" style="max-width: 100px;max-height: 75px" />
                    </a>
                </td>
                <td>{{ goods.goods_name }}</td>
                <td>{{ goods.goods_price }}/{{ goods.goods_unit }}</td>
                <td>{{ goods.goods_repertory }}</td>
                <td>{{ goods.goods_manufacturer }}</td>
                <td>{{ goods.cag.cag_name }}</td>
                <td><a href="{% url 'goods:goods_detail' %}?gid={{ goods.id }}">加入购物车</a></td>
            </tr>
        {% endfor %}
        </table>
        <div style="text-align: center;margin: 5px">
        {% if goods_list.has_previous %}
            <a href="{% url 'goods:show' %}?page_num={{ goods_list.previous_page_number }}">上一页</a>
        {% endif %}
            {% for i in goods_list.paginator.page_range %}
                {% if i == goods_list.number %}
                    <a href="{% url 'goods:show' %}?page_num={{ i }}" style="font-size: 30px;padding: 0 10px">{{ i}}</a>
                {% else %}
                    <a href="{% url 'goods:show' %}?page_num={{ i }}" style="font-size: 20px;padding: 0 10px">{{ i }}</a>
                {% endif %}
            {% endfor %}
        {% if goods_list.has_next %}
            <a href="{% url 'goods:show' %}?page_num={{ goods_list.next_page_number }}">下一页</a>
        {% endif %}
        </div>
    </div>
{% endblock %}